### ISSUE TITLE
Error updating `CompanyAcceptedRatePlan` entity.

### ISSUE THREAD

**Issue by Jaesin** [apigee/apigee-client-php#45]
| Q            | A
| ------------ | ---
| Bug?         | yes
| New Feature? | no
| Version      | 2.0.1

#### Actual Behavior

`\Apigee\Edge\Api\Monetization\Controller\AcceptedRatePlanController::updateSubscription` fails with the following error:

```
{
  "code" : "mint.resourceIdMismatch",
  "message" : "URL id qualifier [674cdd50-140d-459e-8b95-xxxxxxxxxxxx] does not match with the entity id [company-x] or some of these entites may not exist",
  "contexts" : [ ]
}
```

The posted payload is as follows: 

```
{
  "created": "2018-10-03 19:53:04",
  "developer": {
    "id": "company-x"
  },
  "endDate": "2019-02-07 17:01:15",
  "id": "674cdd50-140d-459e-8b95-xxxxxxxxxxxx",
  "prevRecurringFeeDate": "2018-10-04 00:00:00",
  "ratePlan": {
    "id": "foo_plan"
  },
  "renewalDate": "2019-10-04 00:00:00",
  "startDate": "2018-10-04 00:00:00",
  "updated": "2018-12-12 00:00:58"
}
```

#### Expected Behavior

The payload should be using "company" instead of "developer" like the following.

```
{
  "created": "2018-10-03 19:53:04",
  "company": {
    "id": "company-x"
  },
  "endDate": "2019-02-07 17:01:15",
  "id": "674cdd50-140d-459e-8b95-xxxxxxxxxxxx",
  "prevRecurringFeeDate": "2018-10-04 00:00:00",
  "ratePlan": {
    "id": "foo_plan"
  },
  "renewalDate": "2019-10-04 00:00:00",
  "startDate": "2018-10-04 00:00:00",
  "updated": "2018-12-12 00:00:58"
}
```

#### Steps to Reproduce the behavior

- Load a company accepted rate plan.
- Try to update the rate plan.

#### Proposed Solution

- Correct the legal entity key.
- Add a test to verify the payload.

**Comment by Jaesin** [comment]
Quick fix until this can be sorted.

[company-accepted-company-id-fix.patch.txt](https://github.com/apigee/apigee-client-php/files/2847006/company-accepted-company-id-fix.patch.txt)

**Comment by mxr576** [comment]
@llynch00 Can you help me out with some documentation regarding this issue? I tried to Google it but I did not find the exact answer that I was looking for. Based on my experiences all API endpoints related to companies accepts the `{"developer": {"id": "company_name"}}` the request payload and returns the same structure in a response payload only two keys are different.
So this bug surprised me because this endpoint should work as all the others.
I am trying to investigate this by myself with manual testing but your help would be much appreciated.

**Comment by mxr576** [comment]
@Jaesin Can you confirm that `acceptRatePlan()` method call works with companies properly?

**Comment by mxr576** [comment]
@Jaesin Please verify that you have called the method with right argument, especially the `$acceptedRatePlan` parameter's content, because I think if the error would be valid that you have reported you should have got a different error.  Meaning:
`  "message" : "URL id qualifier [674cdd50-140d-459e-8b95-xxxxxxxxxxxx] does not match with the entity id [company-x] or some of these entites may not exist",`
Should mean that the URL contained `674cdd50-140d-459e-8b95-xxxxxxxxxxxx ` as developer (company) ID but you sent `{"developer": {"id" => 'company-x'}}` in the payload. Those values should be in sync.

(Next time please share complete (sanitized if needed) requests and responses that include the called API endpoint with URL and query parameters and request body if there is any. You can use the [apigee_edge_debug.module ](https://www.drupal.org/docs/8/modules/apigee-edge/monitor-apigee-edge-debug-logs) to generate such debug log - do not forgot to add the `{response_formatted}` to the log message.)

**Comment by cnovak** [comment]
Reassigned to @Jaesin so he can respond

**Comment by Jaesin** [comment]
@mxr576 Thanks for the help, I found the issue.

The company ID was wrong when instantiating the controller.
